[package]
name = "starfish_sync"
version = "0.1.0"
edition = "2024"
description = "Starfish privileged host synchronizer"

[dependencies]
anyhow = "1.0.102"
duct = "1.1.1"
libc = "0.2"
starfish_msg = { version = "0.1.0", path = "../starfish_msg" }

[[bin]]
name = "starfish-sync"
path = "src/main.rs"
